# Generated by Django 4.0.6 on 2022-07-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellidopaterno', models.CharField(max_length=45)),
                ('apellidomaterno', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('ciudad', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('totaldeuda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipocliente', models.CharField(choices=[('A', 'Mayor'), ('B', 'Medio'), ('C', 'Bajo')], max_length=1)),
            ],
        ),
    ]
